server:
  port: 8083
spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb+srv://ibrahim234mohammed:Carlsberg1999.@fitness-activity.6u3rrih.mongodb.net/fitnessrecommendation
      #uri: mongodb://localhost:27017/fitnessrecommendation
      database: fitnessrecommendation

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  cloud:
    config:
      enabled: false

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}